---
title: "Research Ideas"
author: "Nicholas A Potter"
date: "`r lubridate::date(Sys.time())`"
output:
  md_document:
    variant: markdown_github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Miscellaneous

* Why do region IO economists not look at standard error of make and use tables?
* Negotiation when agents believe they have the right
* In a market place of free ideas and money with entrenched interests, do we necessarily reach efficiency?
* Is Oligopoly the reason for the lack of producitivity growth in the US?

## Econometrics

* Statistical Validity, Reproducible Resaerch. Should consider the recent papers on statistical validity
* Econometric Theory and Machine Learning

## Water and Natural Resources

* Water and transportation costs. Given two types of countries: water-rich and data/tech-rich, but where transport costs of water are high and transport costs of data/tech are low...
* Market power and water trade globally, locally
* Water as a proxy for gravity since it is heavy

## Open source / collaboration

* Collaborative Economies as a public good
* Does open science engender trust in results?
