---
link-citations: true
bibliography: "`r here::here('library.bib')`"
csl: chicago-author-date.csl
title: Research Statement
author: "Nicholas A. Potter, Washington State University, nicholas.a.potter@wsu.edu"
date: "`r format(Sys.time(), '%b %d, %Y')`"
output: pdf_document
---

## Field and Areas of Interest
My primary fields of interest are environmental and natural resource economics and econometrics. I'm specifically interested in management solutions for scarce water resources and the implications for social welfare, conflict, global trade, and market power. My research focuses on three areas: (1) water markets under different water rights policies as water becomes fully allocated and scarce, (2) mechanisms that drive food producer adaptation to climate stress and water shortages, and (3) water resource management solutions in developing countries and how they affect human conflict and social welfare.

My work in these areas is informed by an interest in bayesian modeling, reproducible research methods and the replicability crisis, and science communication. 

## Research Agenda

**Prior appropriations and water markets under scarcity:** There remains a need for a coherent economic theory of how prior-appropriation water rights have evolved in the Western United States and how best to handle inefficiencies that result from use-it-or-lose-it policies that made sense in earlier times. Working with Jonathan Yoder, I develop a framework for evaluating the behavior of water-rights holders and the implications of water rights policies on the social welfare of different social groups.

**Water scarcity and human conflict:** Work by @HsiangBurkeMiguel2013 suggests that precipitation has a U-shaped impact on human conflict. Both too little and too much water can increase the likelihood of conflict. I'm not sure what direction this will take but it seems like an interesting topic. @AlmerETAL2017 use a disaggregated spatial model to estimate the effect of drought on the likelihood of riots. This research focuses on the mechanisms that drive conflict as a result of water shortages, with a focus on evaluating institutions and property rights structures that reduce the likelihood of conflict.

**Food producer adaptation to changing climate and water resources:** Significant effort has been spent to estimate the effect of projected climate change on agricultural yields and productivity, but the factors that affect how food producers adapt to different climates have not been fully explored. Previous research has found that crop insurance programs reduce the impact of climate on food producers and as a result slow adaptation [AnnanSchlenker2015], but other factors such as crop yield thresholds, investment costs, and social cohesion may also affect how food producers adapt.

**Causal inference and issues of statistical significance:** This is less well defined but here I hope to build on recent work by Susan Athey and others [see for example @AtheyImbens2017; @TranETAL2016] incorporating bayesian statistics and machine learning into causal inference. This is motivated partially by discussions around the "crisis of significance" in social science [@GelmanLoken2013 is a good starting point], and thoughts such as those in @Leamer2010.

**Climate effects on agriculture production and natural resource exctraction:** Climate projections provide a view of future climate in the U.S., but the effects of projected climate remain unknown. Previous efforts have allowed for farmer adaptation but have assumed linear responses [@MendelsohnNordhausShaw1994] or have kept crop types fixed and allowed for non-linear temperature responses to crops [@SchlenkerRoberts2009]. Working with Michael Brady and Kirti Rajagopalan, I develop a methodology to match future climate locations to the most analogous current climate location and estimate future agricultural value. This allows for both non-linear yield responses to temperature as well as farmer adaptation by switching to more climate-appropriate crops as the climate changes.

**Market mechanisms when costs are private and heterogeneous:** Building on @Apesteguia2006, Ana Arrandendo-Espanola and I develop a model of a common pool resource in which firm costs are private and non-homogeneous, and payoffs are not well known. Hence uncertainty is reflected in firm cost and payoff evaluations. This increased uncertainty leads to different responses based on the risk profile of different firms, a difference larger firms can exploit to eliminate smaller firms.

**Freshwater availability and global trade:** One way of thinking about water at global scales is in terms of embedded water: the water needed to produce the output of an area's economy. The concept of embedded water allows for estimation of global water trade flows. These trade flows are significantly affected by freshwater availability, which can serve as a comparative advantage [@Debaere2014]. Following @DangLinKonar2015, I examine embedded water flows in the United States and how those flows have changed in response to periods of drought. 

**Network effects, culture, and attitudes toward environmental conservation:** Minority farmers in the United States take advantage of USDA conservation programs at disproportionately low rates. There are several potential mechanisms that may explain this discrepancy, including lack of awareness, distrust of government, and differences in land ownership. Hayley Chouinard, Michael Brady, Phillip Wandschneider, and I are implementing a randomized controlled trial in which the treatment is a mailing emphasizing individual, social, or environmental benefits of the USDA conservation programs.

## Methodology
My methodological focus is causal inference and choice modeling, often in a spatial framework. I use matching methods, synthetic controls

## Data
Much of my research makes use of large-scale geographically located data on natural resources, agriculture, and historical and projected climate. This is data that is expanding rapidly in both resolution and breadth and offers a rich field for analysis that was previously impossible. I make significant use of cluster computing to process high-resolution data sets. Post GIS allows for distributed analysis over geographical space with datasets that contains millions of objects.

## Future Directions
My future research builds on current efforts and is likely to fall into three areas: (1) statistical validity of climate impacts and incorporating bayesian and machine learning methods to improve identification in causal inference, (2) distortionary effects of market power when resources are scarce, and (3) collaborative economies as a response to scarcity.

In the first case, strong causal inference in complex systems is difficult. Machine learning methods provide improved prediction of counterfactuals, and important perspectives on model generalizability. Probabilistic outcomes under a bayesian framework provide a method for explicitly incorporating uncertainty. Both of these tools are particularly useful in the context of high-resolution global data on climate and natural resources.

For questions of how resource scarcity affects societies, an important factor is the degree of centralization of control over that resource. Natural disasters disproportionately affect those without the resources to take preventative action, and the same is true when resources are scarce. I aim to explore how the distribution of economic power in situations of scarcity affects outcomes.

Lastly, one way that societies respond to scarcity is by developing mechanisms to enforce mutually beneficial actions. While much of the work on collaborative economies to date has focused on motivation and benefit to individuals, collaborative economies also can be interpreted as a group-level response to managing scarcity. This may suggest new mechanisms and frameworks for the management of natural resources and resource scarcity.

## References
